spring:
  application:
    name: orderservice
  profiles:
    active: local
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
user-service:
  url: http://user-service:8082
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/${DB_NAME:order_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL:jdbc:postgresql://order-db:5432/${DB_NAME:order_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver